import { 
    MatToolbarModule, 
    MatButtonModule, 
    MatSidenavModule, 
    MatIconModule, 
    MatListModule, 
    MatTableModule, 
    MatPaginatorModule, 
    MatSortModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatGridListModule, 
    MatExpansionModule,
    MatCheckboxModule,
    MatCardModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatSelectModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSnackBarModule,
    MatDatepickerModule,
    MatNativeDateModule
} from '@angular/material';
import { NgModule } from '@angular/core';

@NgModule({
    imports: [
        MatToolbarModule, 
        MatButtonModule, 
        MatSidenavModule, 
        MatIconModule, 
        MatListModule, 
        MatTableModule, 
        MatPaginatorModule, 
        MatSortModule, 
        MatFormFieldModule, 
        MatInputModule, 
        MatGridListModule, 
        MatExpansionModule,
        MatCheckboxModule,
        MatCardModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatTooltipModule,
        MatSelectModule,
        MatProgressBarModule,
        MatRadioModule,
        MatSnackBarModule,
        MatDatepickerModule,
        MatNativeDateModule
    ],
    exports: [
        MatToolbarModule, 
        MatButtonModule, 
        MatSidenavModule, 
        MatIconModule, 
        MatListModule, 
        MatTableModule, 
        MatPaginatorModule, 
        MatSortModule, 
        MatFormFieldModule, 
        MatInputModule, 
        MatGridListModule, 
        MatExpansionModule,
        MatCheckboxModule,
        MatCardModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatTooltipModule,
        MatSelectModule,
        MatProgressBarModule,
        MatRadioModule,
        MatSnackBarModule,
        MatDatepickerModule,
        MatNativeDateModule
    ]
})

export class MaterialModule {}